# AUTO-GENERATED by second-brain setup --connect
# Forwards `python3 -m tools.gateway <args>` to the second brain's gateway.
# The second brain runs the real gateway; --wiki-root tells it which project called.
# Regenerate with: python3 <second-brain>/tools/setup.py --connect
"""Gateway forwarder to the second brain (devops-solutions-research-wiki)."""

import os, subprocess, sys

_SECOND_BRAIN = '/home/jfortin/devops-solutions-research-wiki'
_VENV_PYTHON = '/home/jfortin/devops-solutions-research-wiki/.venv/bin/python'

sys.exit(subprocess.call(
    [_VENV_PYTHON, "-m", "tools.gateway",
     "--wiki-root", os.getcwd()] + sys.argv[1:],
    cwd=_SECOND_BRAIN,
))
